# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap, QPalette,QFont
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QStyle,QLabel


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(1920, 1178)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         # self.radioButton.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#
#         self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton.setGeometry(QtCore.QRect(260, 520, 64, 64))
#         self.radioButton.setObjectName("radioButton")
#         self.radioButton.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_2.setGeometry(QtCore.QRect(130, 880, 64, 64))
#         self.radioButton_2.setObjectName("radioButton_2")
#         self.radioButton_2.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_3.setGeometry(QtCore.QRect(620, 900, 64, 64))
#         self.radioButton_3.setObjectName("radioButton_3")
#         self.radioButton_3.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_4.setGeometry(QtCore.QRect(920, 820, 64, 64))
#         self.radioButton_4.setObjectName("radioButton_4")
#         self.radioButton_4.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_5.setGeometry(QtCore.QRect(1470, 940, 64, 64))
#         self.radioButton_5.setObjectName("radioButton_5")
#         self.radioButton_5.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_6.setGeometry(QtCore.QRect(890, 590, 64, 64))
#         self.radioButton_6.setObjectName("radioButton_6")
#         self.radioButton_6.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_7.setGeometry(QtCore.QRect(850, 320, 64, 64))
#         self.radioButton_7.setObjectName("radioButton_7")
#         self.radioButton_7.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_8.setGeometry(QtCore.QRect(960, 330, 64, 64))
#         self.radioButton_8.setObjectName("radioButton_8")
#         self.radioButton_8.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_9.setGeometry(QtCore.QRect(840, 80, 64, 64))
#         self.radioButton_9.setObjectName("radioButton_9")
#         self.radioButton_9.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_10.setGeometry(QtCore.QRect(1470, 540, 64, 64))
#         self.radioButton_10.setObjectName("radioButton_10")
#         self.radioButton_10.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#         self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
#         self.radioButton_11.setGeometry(QtCore.QRect(1100, 650, 64, 64))
#         self.radioButton_11.setObjectName("radioButton_11")
#         self.radioButton_11.setStyleSheet("QRadioButton{border-image: url(res/location.png)}")
#
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         # self.radioButton.setText(_translate("MainWindow", "二期运动场"))
#         # self.radioButton_2.setText(_translate("MainWindow", "信息学院"))
#         # self.radioButton_3.setText(_translate("MainWindow", "体育馆"))
#         # self.radioButton_4.setText(_translate("MainWindow", "游泳馆"))
#         # self.radioButton_5.setText(_translate("MainWindow", "电子学院"))
#         #
#



vex=[[260,520,"二期运动场"],       #二期运动场
     [130,880,"信院院楼"],       #信院院楼
     [620,900,"生科院楼"],       #生科院楼
     [920,820,"教学楼群"],       #教学楼群
     [1470,940,"电院院楼"],      #电院院楼
     [890,590,"航院院楼"],       #航院院楼
     [850,320,"体育馆"],       #体育馆
     [960,330,"游泳馆"],       #游泳馆
     [840,80,"新工科大楼"],        #新工科大楼
     [1470,540,"一期运动场"],      #一期运动场
     [1100,650,"小巨蛋"]]       #小巨蛋

spoint=0
epoint=0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2055, 1178)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.rB=[0 for i in range(11)]
        for i in range(11):
            self.rB[i] = QtWidgets.QRadioButton(self.centralwidget)
            self.rB[i].setGeometry(QtCore.QRect(vex[i][0],vex[i][1], 64, 64))
            self.rB[i].setObjectName("radioButton_"+str(i))
            if i == 0:
                self.rB[i].setChecked(True)
            # self.rB[i].toggled.connected(lambda :self.rbstate(self.rB[i],i) )
            self.rB[i].setStyleSheet("QRadioButton{border-image: url(res/location.png)}")

        self.label1=QLabel(self.centralwidget)
        self.label1.move(1700,250)
        self.label1.resize(500,100)
        pe = QPalette()
        pe.setColor(QPalette.WindowText, Qt.red)
        self.label1.setAutoFillBackground(True)
        pe.setColor(QPalette.Window, Qt.yellow)
        # pe.setColor(QPalette.Background,Qt.blue)
        self.label1.setPalette(pe)
        self.label1.setFont(QFont("Roman times", 18, QFont.Bold))
        self.label1.setText("起点是："+str(vex[spoint][2]))

        self.label2 = QLabel(self.centralwidget)
        self.label2.move(1700, 650)
        self.label2.resize(500, 100)
        self.label2.setAutoFillBackground(True)
        self.label2.setPalette(pe)
        self.label2.setFont(QFont("Roman times", 18, QFont.Bold))
        self.label2.setText("终点是：" + str(vex[epoint][2]))


        self.spoint=QtWidgets.QPushButton(self.centralwidget)
        self.spoint.setText("将选中的点设为起点")
        self.spoint.resize(200,100)
        self.spoint.move(1800,100)
        self.spoint.setStyleSheet('QPushButton:pressed {background-color:red;}')
        self.spoint.clicked.connect(self.start)

        self.epoint = QtWidgets.QPushButton(self.centralwidget)
        self.epoint.setText("将选中的点设为终点")
        self.epoint.resize(200, 100)
        self.epoint.move(1800, 500)
        self.epoint.setStyleSheet('QPushButton:pressed {background-color:red;}')
        self.epoint.clicked.connect(self.end)

        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setText("开始导航")
        self.start.setFont(QFont("Roman times", 18, QFont.Bold))
        self.start.resize(200, 100)
        self.start.move(1800, 800)
        self.start.setStyleSheet('QPushButton:pressed {background-color:green;}')
        self.start.clicked.connect(self.end)

        # self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        # print(type(self.radioButton))
        # self.radioButton.setGeometry(QtCore.QRect(260, 520, 64, 64))
        # self.radioButton.setObjectName("radioButton")

        # self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        # self.radioButton_11.setGeometry(QtCore.QRect(1100, 650, 64, 64))
        # self.radioButton_11.setObjectName("radioButton_11")

        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def start(self):
        for i in range(11):
            if self.rB[i].isChecked() == True:
                spoint=i
                print(vex[i][2])
                self.label1.setText("起点是：" + str(vex[spoint][2]))
                break
    def end(self):
        for i in range(11):
            if self.rB[i].isChecked() == True:
                epoint=i
                print(vex[i][2])
                self.label2.setText("终点是：" + str(vex[epoint][2]))
                break

    # def rbstate(self,btn,i):
    #     if btn.isChecked()== True:
    #         flag=i
    #         print(i)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.radioButton.setText(_translate("MainWindow", "二期运动场"))
        # self.radioButton_2.setText(_translate("MainWindow", "信院院楼"))
        # self.radioButton_3.setText(_translate("MainWindow", "生科院楼"))
        # self.radioButton_4.setText(_translate("MainWindow", "教学楼群"))
        # self.radioButton_5.setText(_translate("MainWindow", "电院院楼"))
        # self.radioButton_6.setText(_translate("MainWindow", "航院院楼"))
        # self.radioButton_7.setText(_translate("MainWindow", "体育馆"))
        # self.radioButton_8.setText(_translate("MainWindow", "游泳馆"))
        # self.radioButton_9.setText(_translate("MainWindow", "新工科大楼"))
        # self.radioButton_10.setText(_translate("MainWindow", "一期运动场"))
        # self.radioButton_11.setText(_translate("MainWindow", "小巨蛋"))
